imports:
  - { resource: ../common.yml }

services:
  ebiggio.customer_dni.controller.back_office_settings:
    public: true
    class: Ebiggio\CustomerDNI\Controller\BackOfficeSettings

  ebiggio.customer_dni.form.settings_form:
    public: true
    class: Ebiggio\CustomerDNI\Form\SettingsFormType
    parent: 'form.type.translatable.aware'
    tags:
      - { name: form.type }

  ebiggio.customer_dni.form.settings_form_handler:
    public: true
    class: PrestaShop\PrestaShop\Core\Form\Handler
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@ebiggio.customer_dni.form.settings_data_provider'
      - 'Ebiggio\CustomerDNI\Form\SettingsFormType'
      - 'Settings'

  ebiggio.customer_dni.form.settings_data_configuration:
    public: true
    class: Ebiggio\CustomerDNI\Form\SettingsDataConfiguration
    arguments:
      - '@prestashop.adapter.legacy.configuration'

  ebiggio.customer_dni.form.settings_data_provider:
    public: true
    class: Ebiggio\CustomerDNI\Form\SettingsDataProvider
    arguments:
      - '@ebiggio.customer_dni.form.settings_data_configuration'
