services:
  _defaults:
    public: true

  ebiggio.customer_dni.repository.customer_dni_repository:
    class: Ebiggio\CustomerDNI\Repository\CustomerDNIRepository
    factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
    arguments:
      - Ebiggio\CustomerDNI\Entity\CustomerDNI